{{- include "factory.headers" . }}
---
{{- include "factory.pvcLogsCommonSpec" . }}
  storageClassName: manual
  accessModes:
    - {{ .Values.storage.hostPath.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.hostPath.logsSize }}
