apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Namespace }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - {}
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Namespace }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress
