# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
updates:
  # Go modules - separate block for each directory
  - package-ecosystem: "gomod"
    directory: "/attestation-verifier/src"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      semver-patch-days: 2
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
  
  - package-ecosystem: "gomod"
    directory: "/attestation-manager/src"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      semver-patch-days: 2
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"

  # Docker - separate block for each directory
  - package-ecosystem: "docker"
    directory: "/attestation-manager"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "docker"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
  
  - package-ecosystem: "docker"
    directory: "/attestation-verifier/src/build/image/aas-manager"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "docker"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
  
  - package-ecosystem: "docker"
    directory: "/attestation-verifier/src/build/image/authservice"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "docker"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
  
  - package-ecosystem: "docker"
    directory: "/attestation-verifier/src/build/image/cms"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "docker"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
  
  - package-ecosystem: "docker"
    directory: "/attestation-verifier/src/build/image/hvs"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "docker"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
  
  - package-ecosystem: "docker"
    directory: "/attestation-verifier/src/build/image/tagent"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "docker"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
  
  - package-ecosystem: "docker"
    directory: "/attestation-verifier/utils/tools/containers/init-wait"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "docker"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
  
  - package-ecosystem: "docker"
    directory: "/attestation-verifier/utils/tools/containers/nats"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "docker"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
      semver-patch-days: 3
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gha] "
    labels:
      - "gha"
    reviewers:
      - "srinivasmusti"
      - "pchand20"
      - "vtcao297"
      - "shahmitu"
      - "hemanthsm"
