{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
{{- if .Values.config.tpmOwnerSecret }}
  TPM_OWNER_SECRET: {{ .Values.config.tpmOwnerSecret }}
{{- end }}
{{- if .Values.config.tpmEndorsementSecret }}
  TPM_ENDORSEMENT_SECRET: {{ .Values.config.tpmEndorsementSecret }}
{{- end }}