# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: curl-httpbin
description: Helm chart to install curl-httpbin on Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - curl-httpbin
  - app-orch
  - open-edge-platform
