{{- include "factory.headers" . }}
---
{{- if .Values.global }}
{{- if .Values.global.config.nats.enabled }}
{{- include "factory.createAASRolesAndPermissionSecret" . }}
{{- end }}
{{- else }}
{{- include "factory.createAASRolesAndPermissionSecret" . }}
{{- end }}

