{{- include "factory.headers" . }}
---
{{ include "factory.serviceCommonSpec" . }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ta.containerPort }}
      targetPort: {{ .Values.service.ta.containerPort }}
      protocol: TCP
      name: https
