{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  GLOBAL_ADMIN_USERNAME: {{ .Values.secret.globalAdminUsername }}
  {{- if not .Values.secret.globalAdminPassword }}
  {{- $password := randAlphaNum 16 }}
  {{- $_ := set .Values.secret "globalAdminPassword" $password }}
  GLOBAL_ADMIN_PASSWORD: {{ .Values.secret.globalAdminPassword }}
  {{- else }}
  GLOBAL_ADMIN_PASSWORD: {{ .Values.secret.globalAdminPassword }}
  {{- end }}

