apiVersion: v1
kind: Namespace
metadata:
  name: trusted-compute
---
apiVersion: v1
kind: Namespace
metadata:
  name: kata-deploy
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: attestation-verifier
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/attestation-verifier.tgz
  targetNamespace: trusted-compute
  valuesContent: |-
    attestation-manager:
      env:
        pollDuration: 5
        InformAMServer: "false"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: trusted-workload
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/trusted-workload.tgz
  targetNamespace: kata-deploy
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kata-deploy
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/kata-deploy.tgz
  targetNamespace: kata-deploy

