name: kata-deploy
services:
  kata-deploy:
    image: registry-rs.edgeorchestration.intel.com/edge-orch/trusted-compute/kata-deploy:${VERSION}
    container_name: kata-deploy
    privileged: true
    entrypoint: ["/usr/bin/tc-docker-deploy"]
    volumes:
      - /opt:/host/opt
      - /usr/bin:/host/usr/bin
      - /etc:/host/etc
    environment:
      - DEBUG=false
    restart: unless-stopped
    network_mode: none
