{{- include "factory.headers" . }}
---
{{ if  .Values.global }}
{{- if .Values.global.config.nats.enabled }}
{{- include "factory.serviceCommonSpec" . }}
  type: ClusterIP
  ports:
    - name: {{ .Values.service.natsClient.name }}
      port: {{ .Values.service.natsClient.containerPort }}
    - name: {{ .Values.service.natsCluster.name }}
      port: {{ .Values.service.natsCluster.containerPort }}
{{- end }}
{{- else }}
{{- include "factory.serviceCommonSpec" . }}
  type: ClusterIP
  ports:
    - name: {{ .Values.service.natsClient.name }}
      port: {{ .Values.service.natsClient.containerPort }}
    - name: {{ .Values.service.natsCluster.name }}
      port: {{ .Values.service.natsCluster.containerPort }}
{{- end }}