# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: v1
kind: Service
metadata:
  name: {{ include "attestation-manager.fullname" . }}
  labels:
    {{- include "attestation-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "attestation-manager.selectorLabels" . | nindent 4 }}
