{{- include "factory.headers" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "factory.name" . }}-jobs
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "factory.name" . }}-jobs
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["delete","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "factory.name" . }}-jobs
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
subjects:
  - kind: ServiceAccount
    name: {{ include "factory.name" . }}-jobs
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "factory.name" . }}-jobs
  apiGroup: rbac.authorization.k8s.io
