{{- include "factory.headers" . }}
{{- if .Values.global }}
---
{{ include "factory.pvBaseCommonSpec" . }}
  hostPath:
    path: {{ .Values.global.storage.hostPath.path }}/verifier/{{ .Values.service.directoryName }}/
{{- else }}
---
{{ include "factory.pvBaseCommonSpec" . }}
  hostPath:
    path: {{ .Values.storage.hostPath.path }}/verifier/{{ .Values.service.directoryName }}/
{{- end }}
