{{- include "factory.headers" . }}
---
{{- $secretName := printf "%sdb-credentials" (include "factory.name" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  AAS_DB_USERNAME: {{ .Values.secret.dbUsername }}
  AAS_DB_PASSWORD: {{- if and $existing $existing.data (hasKey $existing.data "AAS_DB_PASSWORD") }} {{ index $existing.data "AAS_DB_PASSWORD" | b64dec | quote }} {{- else }} {{ randAlphaNum 16 | quote }} {{- end }}
