{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if .Values.global }}
  AAS_ADMIN_USERNAME: {{ .Values.global.aas.secret.adminUsername }}
  {{- if not .Values.global.aas.secret.adminPassword }}
  {{- $password := randAlphaNum 16 }}
  {{- $_ := set .Values.global.aas.secret "adminPassword" $password }}
  AAS_ADMIN_PASSWORD: {{ .Values.global.aas.secret.adminPassword }}
  {{- else }}
  AAS_ADMIN_PASSWORD: {{ .Values.global.aas.secret.adminPassword }}
  {{- end }}
  {{- else }}
  AAS_ADMIN_USERNAME: {{ .Values.secret.adminUsername }}
  AAS_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | default (randAlphaNum 16) }}
  {{- end}}
