{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if .Values.global }}
  AAS_ADMIN_USERNAME: {{ .Values.global.aas.secret.adminUsername }}
  AAS_ADMIN_PASSWORD: {{ .Values.global.aas.secret.adminPassword }}
  {{- else }}
  AAS_ADMIN_USERNAME: {{ .Values.secret.adminUsername }}
  AAS_ADMIN_PASSWORD: {{ .Values.secret.adminPassword }}
  {{- end}}
