# templates/cleanup-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-job-am
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: cleanup-am
        image: debian:bullseye-slim
        command: ["sh", "-c", "rm -rf /tmp/attestation-manager/flavor_update"]
        volumeMounts:
        - name: host-volume
          mountPath: /tmp/attestation-manager
      restartPolicy: Never
      volumes:
      - name: host-volume
        hostPath:
          path: /tmp/
