# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---

name: Auto Update PR

# On push to the main branch and support branches, update any branches that are out of date
# and have auto-merge enabled. If the branch is currently out of date with the base branch,
# it must be first manually updated and then will be kept up to date on future runs.
on:
  schedule:
    - cron: '0 3-12 * * *'  # Every hour 8:30am-5:30pm IST (UTC+5:30)
  push:
    branches:
      - main
      - release-*

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-pull-requests:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c  # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Update pull requests
        uses: open-edge-platform/orch-ci/.github/actions/pr_updater@547a9b246177a30455df6b332eded93577a6d5ca  # 2026.1.4
        with:
          github_token: ${{ secrets.SYS_EMF_GH_TOKEN }}