---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge helm charts

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'helm/**'
  workflow_dispatch:

permissions: {}

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@791c0c74ac05e6d972fa6de8c979e854336e9a41  # 0.1.10
    with:
      run_build: false
      run_helm_build: true
      run_helm_push: true
      run_version_tag: true
      prefix_tag_separator: "/"
      project_folder: "helm"
    secrets: inherit  # zizmor: ignore[secrets-inherit]
