---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0


name: Post-Merge ATTESTATION MANAGER

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'attestation-manager/**'
  workflow_dispatch:

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@main
    with:
      run_version_check: false
      run_build: true
      run_docker_build: true
      run_docker_push: true
      run_version_tag: true
      run_artifact: false
      prefix_tag_separator: "/"
      project_folder: "attestation-manager"
    secrets: inherit
