---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0


name: Post-Merge Baremetal Pipeline

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'baremetal/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@d40dfda9598df896aa20cb1dc2c950d6444e8fa7  # 2026.0.19
    with:
      run_version_check: false
      run_build: true
      run_docker_build: false
      run_docker_push: false
      run_version_tag: true
      run_artifact_push: true
      prefix_tag_separator: "/"
      project_folder: "baremetal"
      trivy_image_skip: |
        ghcr.io/github/github-mcp-server:latest,
        ghcr.io/github/gh-aw-mcpg:latest,
        ghcr.io/github/gh-aw-firewall/agent:latest,
        ghcr.io/github/gh-aw-firewall/api-proxy:latest,
        ghcr.io/github/gh-aw-firewall/squid:latest,
        debian@sha256:0a5bf4ecacfc050bad0131c8e1401063fd1e8343a418723f6dbd3cd13a7b9e33
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
      NO_AUTH_ECR_PUSH_USERNAME: ${{ secrets.NO_AUTH_ECR_PUSH_USERNAME }}
      NO_AUTH_ECR_PUSH_PASSWD: ${{ secrets.NO_AUTH_ECR_PUSH_PASSWD }}
      MSTEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
