---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge trusted-vm

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'trusted-vm/**'
  workflow_dispatch:

permissions: {}

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@628dd6e7fd94a3e765e389b5bb43d90fbe3de421  # v0.1.32
    with:
      run_version_check: false
      run_build: true
      run_docker_build: false
      run_docker_push: false
      run_version_tag: false
      prefix_tag_separator: "/"
      project_folder: "trusted-vm"
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      NO_AUTH_ECR_PUSH_USERNAME: ${{ secrets.NO_AUTH_ECR_PUSH_USERNAME }}
      NO_AUTH_ECR_PUSH_PASSWD: ${{ secrets.NO_AUTH_ECR_PUSH_PASSWD }}
      MSTEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
