---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0


name: Post-Merge ATTESTATION MANAGER

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'attestation-manager/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@490a8651344e504bba68a208b1104254046dacd5  # v0.1.65
    with:
      run_version_check: false
      run_build: true
      run_docker_build: true
      run_docker_push: true
      run_version_tag: true
      prefix_tag_separator: "/"
      project_folder: "attestation-manager"
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      NO_AUTH_ECR_PUSH_USERNAME: ${{ secrets.NO_AUTH_ECR_PUSH_USERNAME }}
      NO_AUTH_ECR_PUSH_PASSWD: ${{ secrets.NO_AUTH_ECR_PUSH_PASSWD }}
      MSTEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
