---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge helm charts

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'helm/**'
  workflow_dispatch:

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@main
    with:
      run_security_scans: true
      run_build: false
      run_helm_build: true
      run_helm_push: true
      run_version_tag: true
      prefix_tag_separator: "/"
      project_folder: "helm"
    secrets: inherit
