---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge trusted-vm

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'trusted-vm/**'
  workflow_dispatch:

permissions: {}

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@13722579bc8edfb712203cb8e88fcc404d2218bc  # 0.1.9
    with:
      run_version_check: false
      run_build: true
      run_docker_build: false
      run_docker_push: false
      run_version_tag: false
      prefix_tag_separator: "/"
      project_folder: "trusted-vm"
    secrets: inherit  # zizmor: ignore[secrets-inherit]
