---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge helm charts

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'helm/**'
  workflow_dispatch:

permissions: {}

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@13722579bc8edfb712203cb8e88fcc404d2218bc  # 0.1.9
    with:
      run_build: false
      run_helm_build: true
      run_helm_push: true
      run_version_tag: true
      prefix_tag_separator: "/"
      project_folder: "helm"
    secrets: inherit  # zizmor: ignore[secrets-inherit]
