---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge trusted-vm

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'trusted-vm/**'
  workflow_dispatch:

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@main
    with:
      run_security_scans: true
      run_version_check: true
      run_build: true
      run_docker_build: false
      run_docker_push: false
      run_version_tag: false
      prefix_tag_separator: "/"
      project_folder: "trusted-vm"
    secrets: inherit
