---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge trusted-vm

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'trusted-vm/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@b5930c48c1fcdb6b34ffbcd465cff96dabfbde70  # 2026.0.17
    with:
      run_version_check: false
      run_build: true
      run_docker_build: false
      run_docker_push: false
      run_version_tag: false
      prefix_tag_separator: "/"
      project_folder: "trusted-vm"
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
      NO_AUTH_ECR_PUSH_USERNAME: ${{ secrets.NO_AUTH_ECR_PUSH_USERNAME }}
      NO_AUTH_ECR_PUSH_PASSWD: ${{ secrets.NO_AUTH_ECR_PUSH_PASSWD }}
      MSTEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
