# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-cluster-role
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: cc-operator-controller-manager
  namespace: confidential-containers-system
roleRef:
  kind: ClusterRole
  name: helm-cluster-role
  apiGroup: rbac.authorization.k8s.io
